CSS Fixes for md-dialog
home-assistant/home-assistant-polymer pull request #22638
Opened 2024-11-03 04:49 UTC by balloob

## Breaking change

## Proposed change

Looks like during the conversion to the new dialog some invalid CSS sneaked in.

I noticed it because I was building the demo locally, and the HTML minifier complained about invalid CSS.

I've not tested this PR. Please test and verify that it still works as intended (or feel free to close it / remove the CSS that probably didn't work before)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-11-04 07:08 UTC, wendevlin requested changes

2024-11-04 17:22 UTC, balloob commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
Everything is inside the host though? What does this selector do?

Take a look at this playground: https://developer.mozilla.org/en-US/docs/Web/CSS/:host#try_it

Change the CSS from `:host` to `:host h1` and the selector no longer works

2024-11-04 17:23 UTC, balloob commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
You can use `:host` or you can match a host with a specific class/attribute, like `:host(.warning)`

2024-11-04 17:24 UTC, balloob commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
Docs
- https://developer.mozilla.org/en-US/docs/Web/CSS/:host
- https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context
- https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function

2024-11-04 18:10 UTC, wendevlin commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
😄 🤷 I can just say when you remove it the ha-dialog-header is broken inside an md-dialog. 

I will have a detailed look into it tomorrow.

2024-11-05 08:24 UTC, wendevlin commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
I edited the suggestion, when we specify the slot it work. We use `:host ::slotted` multiple times in the frontend project, it seems to be a special case for `::slotted` and how it overrides global rules.

2024-11-07 19:13 UTC, wendevlin commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
@balloob is this a fine solution for you?

2024-11-09 01:19 UTC, balloob commented on src/components/ha-md-dialog.ts
> +      ::slotted(ha-dialog-header) {
Sure, if you say it works then let's do it 👍

2024-11-11 06:59 UTC, wendevlin approved these changes

2024-11-11 07:11 UTC, merged