Add missing header strings for "automation" and "edit"
home-assistant/home-assistant-polymer pull request #22995
Opened 2024-11-25 15:27 UTC by NoRi2909

In the Tags list the two column headers for the "Create automation" and the "Edit" buttons are missing the strings to translate:

![Screenshot 2024-10-23 15 59 22](https://github.com/user-attachments/assets/0e0fef38-0621-4d10-a939-87f01cc62e97)

Should be
- Create automation
- Edit

Note that both columns are buttons, their tooltips are:

- Create automation with tag
- Edit

## Proposed change

Add the missing strings for translation.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #22498 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-11-25 15:33 UTC, karwosts commented
I don't think this is sufficient, you need to add code to use the label in `ha-config-tags.ts`

2024-11-25 15:52 UTC, NoRi2909 commented
@karwosts As the columns are present with their key names I hoped that mapping them should be enough.
At least all checks have passed …

2024-11-25 16:13 UTC, silamon approved these changes

2024-11-25 16:15 UTC, silamon requested changes
Like mentioned, the labels are not yet used.

2024-11-25 16:24 UTC, NoRi2909 commented
@silamon I'm afraid that using the Github web editor I'm not able to make any additional code changes.

I assume this means closing this PR and you might want to take over with a full dev environment to implement the complete fix?

2024-11-25 16:27 UTC, karwosts commented
I think you can still do it in the web editor. 

Go to your fork, switch to the patch-25 branch, find the file you want to edit, make changes, and commit the change to your existing patch-25 branch.

2024-11-25 16:34 UTC, NoRi2909 commented
For the moment I will not start messing with code, you guys are the pros here.

I'll stick to simple string fixes and the complete German translation including the Android app for the moment.

I'll put the full dev environment on my list for next year. :-)

2024-11-25 16:42 UTC, karwosts commented
I went ahead and added it for you (was kinda curious just to see if github would let me do it in the editor).

Probably could have used a common string for `edit` 🤔

2024-11-25 16:51 UTC, NoRi2909 commented
Cool.

I could replace "Edit" with "[%key:ui::panel::config::tag::edit%]", that's within the same context.

2024-11-26 10:07 UTC, piitaya commented
May I suggest to remove edit button and make the row clickable like any other data table?

2024-11-26 10:16 UTC, NoRi2909 commented
@piitaya That's a great improvement idea but definitely outside of what I can handle.
I'm just the German translator who reports back when he hits some missing strings etc.

2024-11-26 10:17 UTC, piitaya commented
@piitaya Should I take the point? I can open a PR for that.

2024-11-26 10:19 UTC, NoRi2909 commented
@piitaya Sure, go ahead.

2024-11-26 11:03 UTC, piitaya commented
I open a PR : https://github.com/home-assistant/frontend/pull/23003
This one can be closed as we has no need to translate these terms anymore. Thank you @NoRi2909 for the contribution 🙂

2024-11-26 11:03 UTC, closed without merging