Added "Media player volume" card feature.
home-assistant/home-assistant-polymer pull request #23199
Opened 2024-12-07 14:19 UTC by simon-zumbrunnen

## Proposed change

Adds the possibility to add a "Media player volume" feature (slider) to the "Tile card".

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
- type: tile
  entity: media_player.living_room
  features:
    - type: "media-player-volume"
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ x] The code change is tested and works locally.
- [x ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-12-09 06:51 UTC, MindFreeze requested changes

2024-12-09 06:51 UTC, MindFreeze commented on src/panels/lovelace/card-features/hui-media-player-volume-card-feature.ts
> +};
```suggestion
import { MediaPlayerEntityFeature } from "../../../data/media-player";
import { supportsFeature } from "../../../common/entity/supports-feature";

export const supportsMediaPlayerVolumeCardFeature = (stateObj: HassEntity) => {
  const domain = computeDomain(stateObj.entity_id);
  return (
    domain === "media_player" &&
    supportsFeature(stateObj, MediaPlayerEntityFeature.VOLUME_SET)
  );
};
```
Some players (like Chromecast) don't support volume

2024-12-09 06:54 UTC, MindFreeze commented
TBH, I prefer buttons for volume but this is still an awesome feature

2024-12-09 10:38 UTC, simon-zumbrunnen commented
> TBH, I prefer buttons for volume but this is still an awesome feature

You might not be the only one. Would it make sense to call it "Media player volume *slider*" so a second feature called "Media player volume *buttons*" could be created in the future?

2024-12-09 11:56 UTC, MindFreeze commented
Yeah, good idea

2024-12-10 11:12 UTC, MindFreeze submitted a review, later dismissed

2024-12-10 13:32 UTC, MindFreeze approved these changes

2024-12-10 13:36 UTC, merged